[project]
name = "car-dealership-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.3.0",
    "langgraph>=0.3.22",
    "ollama>=0.4.7",
    "pydantic>=2.11.1",
    "ruff>=0.11.2",
]
